<div style="text-align: center;">
    <h1>Project 1</h1>
    <h2>STQD6014 Data Science</h2>
    <h3>Student Name: Ahmad Hathim Ahmad Azman</h3>
    <h3>Student Number: P153146</h3>
</div>

**Create two arrays each of sizes: single 1d array, 3x3, 2x4, 4x2 and 5x5. Hence, you will have ten arrays all together and these arrays must be generated via random number. Name your arrays in order from A to J.**

*Using numpy library: perform at least twenty (20) functions from Table 4-3, Table 4-4, Table 4-5 and Table 4-7 from Python for Data Analysis book.*

You must:
1. Perform operation on single array
2. Perform operation on two arrays of same size (eg. multiplication, etc.)
3. Perform operation on two arrays of different size (eg. dot product between array of size 2x4 and 4x2

Note: you must include all arrays created.


In [326]:
import numpy as np
import pandas as pd
import random

import warnings
warnings.filterwarnings('ignore')
np.random.seed(52)

In [327]:
# 1d array
A = np.random.rand(15)
B = np.random.rand(15)

# 3x3 array
C = np.random.rand(3, 3)
D = np.random.rand(3, 3)

# 2x4 array
E = np.random.rand(2, 4)
F = np.random.rand(2, 4)

# 4x2 array
G = np.random.rand(4, 2)
H = np.random.rand(4, 2)

# 5x5 array
I = np.random.rand(5, 5)
J = np.random.rand(5, 5)

total_array_list = [A, B, C, D, E, F, G, H, I, J]
diff_size1 = [C, E, G, I]
diff_size2 = [D, F, H, J]
can_multiply1 = [E, G]
can_multiply2 = [F, H]
one_d = [A, B]
three_by_three = [C, D]
two_by_four = [E, F]
four_by_two = [G, H]
five_by_five = [I, J]

In [328]:
for i in array_list:
    print(f"array {i.shape}\n{i}\n")

array (15,)
[0.74216077 0.26062796 0.34668829 0.47722608 0.66817015 0.28129537
 0.70400133 0.88536344 0.3433904  0.85130998 0.50986597 0.54422691
 0.80772018 0.57332744 0.21377624]

array (15,)
[1.44527526e-04 7.12015627e-01 1.04141511e-01 5.57474230e-01
 9.57611702e-01 3.75789341e-01 5.11682945e-01 4.62529111e-01
 9.55985411e-01 3.47329261e-01 1.33560270e-01 9.83509426e-01
 3.71402787e-02 6.30040325e-01 3.36711995e-01]

array (3, 3)
[[0.6839525  0.81509105 0.74432428]
 [0.95321702 0.60157791 0.53808659]
 [0.91585076 0.62939159 0.74276137]]

array (3, 3)
[[0.38465033 0.67042276 0.05905943]
 [0.82588942 0.48237128 0.36190692]
 [0.19513155 0.63085626 0.51215883]]

array (2, 4)
[[0.93292292 0.15923918 0.7294912  0.28392443]
 [0.7662561  0.61736128 0.76324449 0.76224293]]

array (2, 4)
[[0.29530824 0.63140388 0.71517238 0.01429599]
 [0.04382331 0.45662417 0.11148771 0.73971496]]

array (4, 2)
[[0.98810487 0.44324901]
 [0.98650219 0.46501372]
 [0.49613857 0.19190942]
 [0.61166523 0.5569498 

# Unary Functions

In [329]:
np.abs(A)

array([0.82311034, 0.02611798, 0.21077064, 0.61842177, 0.09828447,
       0.62013131, 0.05389022, 0.96065406, 0.98042937, 0.52112765,
       0.63655334, 0.76475695, 0.76495529, 0.41768558, 0.76880531])

In [330]:
np.sqrt(C)

array([[0.71457416, 0.89227773, 0.66736609],
       [0.86201329, 0.28062265, 0.69831602],
       [0.65908167, 0.49604228, 0.92824604]])

In [331]:
np.square(E)

array([[0.6199756 , 0.44214395, 0.51869405, 0.2907963 ],
       [0.2227344 , 0.81123798, 0.14025962, 0.27855853]])

In [332]:
np.exp(G)

array([[2.4379999 , 1.37758671],
       [1.99376807, 1.06063531],
       [1.22358352, 2.06073305],
       [2.1212593 , 1.34363836]])

In [333]:
np.log(I)

array([[-0.76536318, -0.15650901, -0.01573633, -0.73871466, -0.62230787],
       [-0.24563896, -0.20478159, -1.92651354, -1.06935549, -0.36295188],
       [-1.67014709, -0.78652491, -0.03002314, -0.00567026, -0.28700446],
       [-0.66886657, -0.66403054, -2.67115721, -0.02924102, -0.04623201],
       [-0.24844045, -0.16429152, -0.91787773, -0.22699614, -4.03584659]])

# Binary Universal Functions

In [334]:
np.add(A,5)

array([5.82311034, 5.02611798, 5.21077064, 5.61842177, 5.09828447,
       5.62013131, 5.05389022, 5.96065406, 5.98042937, 5.52112765,
       5.63655334, 5.76475695, 5.76495529, 5.41768558, 5.76880531])

In [335]:
np.subtract(D,8)

array([[-7.97997744, -7.54917329, -7.95257713],
       [-7.5022725 , -7.141226  , -7.66518434],
       [-7.09840997, -7.87711245, -7.84256625]])

In [336]:
np.multiply(A,B)

array([0.34834174, 0.02418796, 0.14373008, 0.22786096, 0.0844175 ,
       0.23595728, 0.00511711, 0.31210758, 0.40698818, 0.38681948,
       0.41879409, 0.15395845, 0.61845711, 0.32846896, 0.30363169])

In [337]:
np.divide(C,D)

array([[25.50204657,  1.76599905,  9.39161749],
       [ 1.49291915,  0.09169941,  1.45645895],
       [ 0.48180285,  2.0023016 ,  5.47303698]])

In [338]:
np.divide(E,F)

array([[1.13375485, 1.56247332, 1.12782724, 0.90734129],
       [1.03888887, 0.98352337, 0.50333143, 0.56782626]])

In [339]:
np.power(G,3)

array([[7.07771963e-01, 3.28704676e-02],
       [3.28546635e-01, 2.04004420e-04],
       [8.21597859e-03, 3.78029937e-01],
       [4.25275844e-01, 2.57720065e-02]])

In [340]:
np.greater(A,B)

array([ True, False, False,  True, False,  True, False,  True,  True,
       False, False,  True, False, False,  True])

In [341]:
np.less_equal(C,D)

array([[False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [342]:
np.maximum(E,F)

array([[0.78738529, 0.66493906, 0.72020417, 0.59432468],
       [0.47194745, 0.91577642, 0.7440674 , 0.9294858 ]])

In [343]:
np.minimum(G,H)

array([[0.89117799, 0.00436327],
       [0.34974214, 0.05886808],
       [0.20178386, 0.72306177],
       [0.28024548, 0.29538113]])

# Basic array statistical methods

In [344]:
np.sum(A)

8.265694282268383

In [345]:
np.mean(C)

0.5115224247833164

In [346]:
np.std(E)

0.1643096094566645

In [347]:
np.var(G)

0.08243849120045141

In [348]:
np.cumsum(I)

array([ 0.46516496,  1.32028878,  2.30467562,  2.78240318,  3.31910755,
        4.10131213,  4.9161374 ,  5.06179253,  5.40502219,  6.1006421 ,
        6.28886148,  6.74428617,  7.71470925,  8.70905504,  9.45956341,
        9.97185231, 10.48662465, 10.55579678, 11.52697914, 12.48179955,
       13.26181586, 14.11031049, 14.5096762 , 15.30660005, 15.32427077])

In [349]:
np.cumprod(J)

array([1.67443755e-01, 3.35846176e-02, 8.08578152e-03, 6.23171060e-04,
       4.56057845e-04, 4.70450751e-05, 1.95080050e-05, 4.31488902e-06,
       4.05566091e-06, 2.05159845e-06, 1.24902443e-06, 7.28967035e-07,
       3.59969855e-07, 6.00479502e-08, 4.79675416e-08, 3.87328314e-08,
       2.53982472e-08, 3.26232879e-09, 1.87731627e-09, 5.29040419e-10,
       1.37708844e-10, 8.42621288e-11, 5.26198263e-11, 1.98261836e-11,
       8.27516792e-12])

# Commonly used `numpy.linalg` functions

In [351]:
np.diag(C)

array([0.51061623, 0.07874907, 0.86164072])

In [352]:
np.diag(I)

array([0.46516496, 0.81482527, 0.97042308, 0.97118236, 0.01767071])

In [354]:
np.dot(E,G)

array([[1.71137685, 0.97140729],
       [1.51455852, 0.63089602]])

In [356]:
np.dot(G,E)

array([[0.85288088, 0.88109917, 0.7617989 , 0.64964   ],
       [0.57109924, 0.51184721, 0.51900669, 0.40317016],
       [0.50012881, 0.78542667, 0.41612126, 0.49043522],
       [0.73152592, 0.76608686, 0.65222461, 0.56142351]])

In [358]:
np.dot(C,D)

array([[0.80804225, 0.96865191, 0.36089902],
       [0.49372978, 0.4625476 , 0.13837661],
       [0.90801406, 0.51302709, 0.23863534]])

In [360]:
np.dot(D,C)

array([[0.36581821, 0.06311211, 0.26962258],
       [1.03771441, 0.5462822 , 0.9289445 ],
       [0.62006761, 0.76622461, 0.59712477]])

In [367]:
from numpy import linalg
linalg.inv(C)

array([[ 0.17290757,  1.91167869, -1.17128887],
       [ 1.4208845 , -0.81751951, -0.27177275],
       [-0.49293052, -0.73029783,  1.82868149]])

In [369]:
linalg.inv(D)

array([[  1.36650381,  -0.94651222,   1.60133121],
       [  3.24727628,  -0.57539209,   0.24553253],
       [-10.36039654,   5.86960882,  -3.01026404]])

In [372]:
linalg.solve(C,D)

array([[-0.10106527,  1.57571448,  0.46385933],
       [-0.6234798 , -0.09488931, -0.24912211],
       [ 1.27536196, -0.62466484,  0.02000485]])

In [373]:
linalg.solve(I,J)

array([[-1.58123484,  1.98305019,  3.1757339 ,  4.65435389,  2.35820987],
       [ 1.25052335, -1.75094855, -2.87617987, -3.85482632, -2.05086695],
       [-0.69103872,  0.52893132,  1.31027585,  1.1332549 ,  1.37042254],
       [ 0.88541788,  0.42386492,  0.08537842, -0.56135804, -0.29507385],
       [ 0.1693435 ,  0.09733454, -0.20047849,  0.67261689,  0.3364267 ]])