<div style="text-align: center;">
    <h1>Project 1</h1>
    <h2>STQD6014 Data Science</h2>
    <h3>Student Name: Ahmad Hathim Ahmad Azman</h3>
    <h3>Student Number: P153146</h3>
</div>

**Create two arrays each of sizes: single 1d array, 3x3, 2x4, 4x2 and 5x5. Hence, you will have ten arrays all together and these arrays must be generated via random number. Name your arrays in order from A to J.**

*Using numpy library: perform at least twenty (20) functions from Table 4-3, Table 4-4, Table 4-5 and Table 4-7 from Python for Data Analysis book.*

You must:
1. Perform operation on single array
2. Perform operation on two arrays of same size (eg. multiplication, etc.)
3. Perform operation on two arrays of different size (eg. dot product between array of size 2x4 and 4x2

Note: you must include all arrays created.


In [96]:
import numpy as np
import pandas as pd
import random

import warnings
warnings.filterwarnings('ignore')
np.random.seed(52)

In [225]:
# 1d array
A = np.random.rand(15)
B = np.random.rand(15)

# 3x3 array
C = np.random.rand(3, 3)
D = np.random.rand(3, 3)

# 2x4 array
E = np.random.rand(2, 4)
F = np.random.rand(2, 4)

# 4x2 array
G = np.random.rand(4, 2)
H = np.random.rand(4, 2)

# 5x5 array
I = np.random.rand(5, 5)
J = np.random.rand(5, 5)

total_array_list = [A, B, C, D, E, F, G, H, I, J]
diff_size1 = [C, E, G, I]
diff_size2 = [D, F, H, J]
can_multiply1 = [E, G]
can_multiply2 = [F, H]
one_d = [A, B]
three_by_three = [C, D]
two_by_four = [E, F]
four_by_two = [G, H]
five_by_five = [I, J]

In [152]:
for i in array_list:
    print(f"array {i.shape}\n{i}\n")

array (15,)
[0.74216077 0.26062796 0.34668829 0.47722608 0.66817015 0.28129537
 0.70400133 0.88536344 0.3433904  0.85130998 0.50986597 0.54422691
 0.80772018 0.57332744 0.21377624]

array (15,)
[1.44527526e-04 7.12015627e-01 1.04141511e-01 5.57474230e-01
 9.57611702e-01 3.75789341e-01 5.11682945e-01 4.62529111e-01
 9.55985411e-01 3.47329261e-01 1.33560270e-01 9.83509426e-01
 3.71402787e-02 6.30040325e-01 3.36711995e-01]

array (3, 3)
[[0.6839525  0.81509105 0.74432428]
 [0.95321702 0.60157791 0.53808659]
 [0.91585076 0.62939159 0.74276137]]

array (3, 3)
[[0.38465033 0.67042276 0.05905943]
 [0.82588942 0.48237128 0.36190692]
 [0.19513155 0.63085626 0.51215883]]

array (2, 4)
[[0.93292292 0.15923918 0.7294912  0.28392443]
 [0.7662561  0.61736128 0.76324449 0.76224293]]

array (2, 4)
[[0.29530824 0.63140388 0.71517238 0.01429599]
 [0.04382331 0.45662417 0.11148771 0.73971496]]

array (4, 2)
[[0.98810487 0.44324901]
 [0.98650219 0.46501372]
 [0.49613857 0.19190942]
 [0.61166523 0.5569498 

# Unary Functions

In [153]:
def unary_fx(x : np.array):
    '''
    a function that runs all unary functions on a given array
    
    abs() and fabs() : Compute the absolute value element-wise for integer, floatingpoint,
                        or complex values
    sqrt()           : Compute the square root of each element
    square()         : Compute the square of each element
    exp()            : Compute the exponent of each element
    log()            : Compute the natural logarithm of each element
    log10()          : Compute the common logarithm of each element
    log2()           : Compute the binary logarithm of each element
    log1p()          : Compute the natural logarithm of one plus each element
    sign()           : Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)
    ceil()           : Compute the ceiling of each element
    floor()          : Compute the floor of each element
    rint()           : Round elements to the nearest integer
    modf()           : Return fractional and integral parts of array as separate array
    isnan()          : Return True if the value is NaN, False otherwise
    isfinite()       : Return True if the value is finite, False otherwise
    isinf()          : Return True if the value is infinity, False otherwise
    cos()            : Compute the cosine of each element
    cosh()           : Compute the hyperbolic cosine of each element
    sin()            : Compute the sine of each element
    sinh()           : Compute the hyperbolic sine of each element
    tan()            : Compute the tangent of each element
    tanh()           : Compute the hyperbolic tangent of each element
    arccos()         : Compute the inverse cosine of each element
    arccosh()        : Compute the inverse hyperbolic cosine of each element
    arcsin()         : Compute the inverse sine of each element
    arcsinh()        : Compute the inverse hyperbolic sine of each element
    arctan()         : Compute the inverse tangent of each element
    arctanh()        : Compute the inverse hyperbolic tangent of each element
    logical_not()    : Compute the truth value of not x element-wise
    '''
    unary_fx_dict ={
        'Absolute Value': np.abs(x),
        'Float Abs Value': np.fabs(x),
        'Square Root': np.sqrt(x),
        'Square': np.square(x),
        'Exponential': np.exp(x),
        'Natural log': np.log(x),
        'log10': np.log10(x),
        'log2': np.log2(x),
        'log(1+x)': np.log1p(x),
        'Sign': np.sign(x),
        'Ceiling': np.ceil(x),
        'Floor': np.floor(x),
        'Round nearest Int': np.rint(x),
        'Fractional and Integral': np.modf(x),
        'is NaN': np.isnan(x),
        'is finite': np.isfinite(x),
        'is inf': np.isinf(x),
        'cos': np.cos(x),
        'cosh': np.cosh(x),
        'sin': np.sin(x),
        'sinh': np.sinh(x),
        'tan': np.tan(x),
        'tanh': np.tanh(x),
        'arccos': np.arccos(x),
        'arccosh': np.arccosh(x),
        'arcsin': np.arcsin(x),
        'arcsinh': np.arcsinh(x),
        'arctan': np.arctan(x),
        'arctanh': np.arctanh(x),
        'logical_not': np.logical_not(x)
    }
    return unary_fx_dict

In [276]:
def random_choice(x : list, y : int, fx):
    '''
    a function that takes in an array and a number and returns number of random choice of unary function

    Parameters:
    x : list : list of  array
    y : int : number of random choices to return
    fx : function : a function that runs all functions on a given array
    '''
    if len(x) > 1:
        for b in x:
            unary_fx_dict = fx(b)
            for i in range(y):
                random_choice = np.random.choice(list(unary_fx_dict.keys()), replace=False)
                print(f"""
{random_choice}:
{unary_fx_dict[random_choice]}
                    """)
            print(f'{'*'*50}')
    else:
        unary_fx_dict = fx(x)
        for i in range(y):
            random_choice = np.random.choice(list(unary_fx_dict.keys()), replace=False)
            print(f"""
{random_choice}:
{unary_fx_dict[random_choice]}
                    """)
            print(f'{'*'*50}')
        

## 1. Perform operation on single array

In [277]:
arr_selection = 5
fx_selection = 4
selected_arrays = random.sample(total_array_list, arr_selection)
for i, arr in enumerate(selected_arrays):
    print(f"Selected Array {i + 1}:\n{arr.shape}\n{arr}")
    random_choice(x=[arr], y=fx_selection, fx=unary_fx)

Selected Array 1:
(2, 4)
[[0.43708335 0.47375514 0.64303437 0.39134   ]
 [0.57665114 0.07394579 0.1952765  0.42283307]]

arcsin:
[[[0.4523533  0.49354993 0.69845386 0.40208728]
  [0.61462371 0.07401334 0.19653936 0.43656934]]]
                    
**************************************************

Floor:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
                    
**************************************************

arcsin:
[[[0.4523533  0.49354993 0.69845386 0.40208728]
  [0.61462371 0.07401334 0.19653936 0.43656934]]]
                    
**************************************************

Square:
[[[0.19104185 0.22444393 0.4134932  0.153147  ]
  [0.33252654 0.00546798 0.03813291 0.17878781]]]
                    
**************************************************
Selected Array 2:
(3, 3)
[[0.88940761 0.84812197 0.29024164]
 [0.48830269 0.39021075 0.68896118]
 [0.43409192 0.45255215 0.30938725]]

arcsin:
[[[1.0960476  1.01243038 0.29447933]
  [0.51014374 0.40086048 0.76005483]
  [0.4490300

# Binary Universal Functions

In [187]:
def BUN_fx(x : list):
    '''
    a function that runs all binary universal functions on a given array

    add()                       : Add corresponding elements in arrays
    subtract()                  : Subtract elements in second array from first array
    multiply()                  : Multiply array elements
    divide() and floor_divide() : Divide first array by second array
    power()                     : Raise elements in first array to powers indicated in second array
    maximum(), fmax()           : Element-wise maximum between two arrays, ignoring any NaNs
    minimum(), fmin()           : Element-wise minimum between two arrays, ignoring any NaNs
    mod()                       : Element-wise modulus (remainder of division)
    copysign()                  : Copy sign of values in second argument to values in first argument
   
    greater(), greater_equal(), 
    less(), less_equal(), 
    equal(), not_equal()        : Perform element-wise comparison
    
    logical_and(), logical_or(),
    logical_xor()               : Perform element-wise logical operations
    '''
    try:
        binary_fx_dict = {
            'Addition': np.add(x[0], x[1]),
            'Subtraction': np.subtract(x[0], x[1]),
            'Multiplication': np.multiply(x[0], x[1]),
            'Division': np.divide(x[0], x[1]),
            'Floor Division': np.floor_divide(x[0], x[1]),
            'Power': np.power(x[0], x[1]),
            'Maximum': np.maximum(x[0], x[1]),
            'Minimum': np.minimum(x[0], x[1]),
            'Modulus': np.mod(x[0], x[1]),
            'Copy Sign': np.copysign(x[0], x[1]),
            'Greater': np.greater(x[0], x[1]),
            'Greater Equal': np.greater_equal(x[0], x[1]),
            'Less': np.less(x[0], x[1]),
            'Less Equal': np.less_equal(x[0], x[1]),
            'Equal': np.equal(x[0], x[1]),
            'Not Equal': np.not_equal(x[0], x[1]),
            'Logical And': np.logical_and(x[0], x[1]),
            'Logical Or': np.logical_or(x[0], x[1]),
            'Logical Xor': np.logical_xor(x[0], x[1])
        }
        return binary_fx_dict
    except ValueError as e:
        print(e)
    

## 2. Perform operation on two arrays of same size (eg. multiplication, etc.)

In [278]:
arr_selection = 2
fx_selection = 5
selected_arrays = random.sample(three_by_three, arr_selection)
print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=BUN_fx)


Selected Arrays:
1.(3, 3) 
[[0.88940761 0.84812197 0.29024164]
 [0.48830269 0.39021075 0.68896118]
 [0.43409192 0.45255215 0.30938725]]

2. (3, 3) 
[[0.3105317  0.01514511 0.5432083 ]
 [0.75869715 0.98822036 0.00264909]
 [0.10068915 0.4574142  0.99737776]] 
**************************************************

Modulus:
[0.40110492 0.06770047 0.29024164]
                    

Minimum:
[0.48830269 0.39021075 0.29024164]
                    

Less:
[False False  True]
                    

Addition:
[1.3777103  1.23833272 0.97920282]
                    

Greater:
[ True  True False]
                    
**************************************************

Logical Xor:
[False False False]
                    

Floor Division:
[  0.   0. 205.]
                    

Modulus:
[3.10531700e-01 1.51451107e-02 1.43994000e-04]
                    

Equal:
[False False False]
                    

Not Equal:
[ True  True  True]
                    
**************************************************


In [279]:
arr_selection = 2
fx_selection = 5

selected_arrays = random.sample(five_by_five, arr_selection)
print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=BUN_fx)


Selected Arrays:
1.(5, 5) 
[[0.63010319 0.59057246 0.97111654 0.20958584 0.86434178]
 [0.55946979 0.87276329 0.39998224 0.01793598 0.20163037]
 [0.25024173 0.40415036 0.48792359 0.05961492 0.82423812]
 [0.69754042 0.90288902 0.02927935 0.31077881 0.07910332]
 [0.78906313 0.83190555 0.41086511 0.05401791 0.06628821]]

2. (5, 5) 
[[0.10391822 0.78147103 0.69868484 0.89960724 0.67644656]
 [0.36703197 0.40651877 0.31813431 0.99148652 0.75068003]
 [0.38762222 0.77545008 0.11361636 0.75867925 0.42385031]
 [0.08703285 0.24031407 0.91515096 0.88885018 0.79130671]
 [0.29752811 0.56948558 0.53151203 0.52419694 0.561722  ]] 
**************************************************

Maximum:
[0.63010319 0.87276329 0.97111654 0.20958584 0.86434178]
                    

Logical Or:
[ True  True  True  True  True]
                    

Logical Or:
[ True  True  True  True  True]
                    

Greater:
[ True False  True  True  True]
                    

Floor Division:
[ 1.  0.  2. 11.  4.]
    

In [280]:
arr_selection = 2
fx_selection = 5

selected_arrays = random.sample(two_by_four, arr_selection)
print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=BUN_fx)


Selected Arrays:
1.(2, 4) 
[[0.81361709 0.85126525 0.20160383 0.88540956]
 [0.94788251 0.99991377 0.68214977 0.16214099]]

2. (2, 4) 
[[0.43708335 0.47375514 0.64303437 0.39134   ]
 [0.57665114 0.07394579 0.1952765  0.42283307]] 
**************************************************

Logical And:
[ True  True  True  True]
                    

Equal:
[False False False False]
                    

Greater:
[False False False  True]
                    

Not Equal:
[ True  True  True  True]
                    

Modulus:
[0.81361709 0.85126525 0.20160383 0.0747046 ]
                    
**************************************************

Power:
[0.62048455 0.94625586 0.91738713 0.67254053]
                    

Power:
[0.62048455 0.94625586 0.91738713 0.67254053]
                    

Less Equal:
[ True False False  True]
                    

Multiplication:
[0.25204461 0.0350322  0.1255695  0.1654715 ]
                    

Minimum:
[0.43708335 0.07394579 0.1952765  0.39134   ]
        

In [281]:
arr_selection = 2
fx_selection = 5

selected_arrays = random.sample(four_by_two, arr_selection)
print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=BUN_fx)


Selected Arrays:
1.(4, 2) 
[[0.35962622 0.7963181 ]
 [0.60623123 0.38959353]
 [0.19741157 0.01166917]
 [0.84594256 0.50675782]]

2. (4, 2) 
[[0.19861146 0.67555357]
 [0.54835062 0.43854009]
 [0.38683331 0.21845029]
 [0.55514507 0.70710952]] 
**************************************************

Floor Division:
[0. 2.]
                    

Subtraction:
[-0.24660501  0.40672457]
                    

Multiplication:
[0.21801665 0.31024038]
                    

Logical And:
[ True  True]
                    

Copy Sign:
[0.35962622 0.7963181 ]
                    
**************************************************

Greater:
[False  True]
                    

Modulus:
[0.19861146 0.23701348]
                    

Copy Sign:
[0.19861146 0.67555357]
                    

Greater Equal:
[False  True]
                    

Subtraction:
[-0.34973917  0.23701348]
                    
**************************************************


## 3. Perform operation on two arrays of different size (eg. dot product between array of size 2x4 and 4x2

In [268]:
arr_selection = 2
fx_selection = 5
try:
    selected_arrays = random.sample(can_multiply2, arr_selection)
    print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
    random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=BUN_fx)

except AttributeError as e:
    print("Unable to perform binary operations on arrays of different sizes")


Selected Arrays:
1.(4, 2) 
[[0.19861146 0.67555357]
 [0.54835062 0.43854009]
 [0.38683331 0.21845029]
 [0.55514507 0.70710952]]

2. (2, 4) 
[[0.81361709 0.85126525 0.20160383 0.88540956]
 [0.94788251 0.99991377 0.68214977 0.16214099]] 
**************************************************

Greater:
[False  True]
                

Logical Xor:
[False False]
                

Logical Xor:
[False False]
                

Less:
[ True False]
                

Not Equal:
[ True  True]
                
**************************************************

Division:
[0.85835226 0.85133866 0.29554188 5.46073854]
                

Subtraction:
[-0.13426542 -0.14864852 -0.48054594  0.72326857]
                

Power:
[0.82241069 0.85127707 0.33540073 0.98046007]
                

Minimum:
[0.81361709 0.85126525 0.20160383 0.16214099]
                

Greater:
[False False False  True]
                
**************************************************


# Basic array statistical methods

In [169]:
def BAS_methods(x : np.array):
    temp = pd.DataFrame()
    '''
    a function that runs all basic array statistical methods on a given array
    
    sum()                   : Sum of all the elements in the array or along an axis; zero-length arrays have sum 0
    mean()                  : Arithmetic mean; zero-length arrays have NaN mean
    std() and var()         : Standard deviation and variance, respectively, with optional degrees of freedom adjustment
                              (default denominator n)
    min()and max()          : Minimum and maximum
    argmin() and argmax()   : Indices of minimum and maximum elements, respectively
    cumsum()                : Cumulative sum of elements starting from 0
    cumprod()               : Cumulative product of elements starting from 1
    '''
    temp['Shape'] = [x.shape]
    temp['Sum'] = [x.sum()]
    temp['Mean'] = [x.mean()]
    temp['Standard Deviation'] = [x.std()]
    temp['Variance'] = [x.var()]
    temp['Minimum'] = [x.min()]
    temp['Maximum'] = [x.max()]
    temp['ArgMin'] = [x.argmin()]
    temp['ArgMax'] = [x.argmax()]
    temp['CumSum'] = [x.cumsum()]
    temp['CumProd'] = [x.cumprod()]
    return temp

In [172]:
BAS_collection = pd.DataFrame()
for i in total_array_list:
    BAS_temp = BAS_methods(i)
    BAS_collection = pd.concat([BAS_collection, BAS_temp], ignore_index=True)

BAS_collection

Shape        Sum      Mean  Standard Deviation  Variance   Minimum  \
0   (15,)   8.194685  0.546312            0.340402  0.115874  0.002039   
1   (15,)   7.542258  0.502817            0.222758  0.049621  0.080913   
2  (3, 3)   3.805111  0.422790            0.222741  0.049613  0.083106   
3  (3, 3)   3.278411  0.364268            0.234702  0.055085  0.039468   
4  (2, 4)   5.866109  0.733264            0.294337  0.086634  0.139012   
5  (2, 4)   4.222226  0.527778            0.330727  0.109380  0.068424   
6  (4, 2)   3.748531  0.468566            0.318401  0.101379  0.018830   
7  (4, 2)   4.648274  0.581034            0.224666  0.050475  0.216677   
8  (5, 5)  11.232494  0.449300            0.286449  0.082053  0.044912   
9  (5, 5)  14.304084  0.572163            0.276938  0.076695  0.076661   

    Maximum  ArgMin  ArgMax  \
0  0.985709      11      14   
1  0.928062       0      10   
2  0.779919       2       3   
3  0.899846       4       2   
4  0.999048       0       6   
5  0.944646       3       2   
6  0.934091       2       0   
7  0.846512       4       6   
8  0.961437       7      15   
9  0.979941      15      16   

                                              CumSum  \
0  [0.7744455504372192, 1.7143197622879163, 2.200...   
1  [0.0809127203629435, 0.31693052602195926, 0.81...   
2  [0.41412449657738615, 1.0827647302002985, 1.16...   
3  [0.4000420829653829, 0.80089906089864, 1.70074...   
4  [0.13901203164805154, 0.9688893147765505, 1.77...   
5  [0.7021427927169929, 0.8684813469651568, 1.813...   
6  [0.9340906531788103, 1.2070205722141607, 1.225...   
7  [0.7947743331443311, 1.1450763826899717, 1.921...   
8  [0.4732128767691933, 1.3682388585120695, 1.889...   
9  [0.26285432207593173, 0.5269598849385223, 0.81...   

                                             CumProd  
0  [0.7744455504372192, 0.7278814013384607, 0.354...  
1  [0.0809127203629435, 0.019096842709963487, 0.0...  
2  [0.41412449657738615, 0.27690030014047445, 0.0...  
3  [0.4000420829653829, 0.16035966042362873, 0.14...  
4  [0.13901203164805154, 0.11536292714625793, 0.0...  
5  [0.7021427927169929, 0.11679341701631282, 0.11...  
6  [0.9340906531788103, 0.2549412863437702, 0.004...  
7  [0.7947743331443311, 0.27841107782672886, 0.21...  
8  [0.4732128767691933, 0.42353781960371795, 0.22...  
9  [0.26285432207593173, 0.06942128868272862, 0.0...

# Commonly used `numpy.linalg` functions

In [254]:
def linalg_func(x,**kwargs):
    '''
    a function that runs all linear algebra functions on a given array

    diag()            : Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
    dot()             : Matrix multiplication
    trace()           : Compute the sum of the diagonal elements
    det()             : Compute the matrix determinant
    eig()             : Compute the eigenvalues and eigenvectors of a square matrix
    inv()             : Compute the inverse of a square matrix
    pinv()            : Compute the Moore-Penrose pseudo-inverse of a matrix
    qr()              : Compute the QR decomposition
    svd()             : Compute the singular value decomposition (SVD)
    solve()           : Solve the linear system Ax = b for x, where A is a square matrix
    lstsq()           : Compute the least-squares solution to Ax = b
    '''
    for key, value in kwargs.items():
        if x.shape[1] == value.shape[1]:
            linal_fx_dict = {
                'Diagonal': np.diag(x),
                'Dot': np.dot(x, value),
                'Trace': np.trace(x),
                'Determinant': np.linalg.det(x),
                'Eigenvalues': np.linalg.eig(x),
                'Inverse': np.linalg.inv(x),
                'Pseudo Inverse': np.linalg.pinv(x),
                'QR': np.linalg.qr(x),
                'SVD': np.linalg.svd(x),
                'Solve': np.linalg.solve(x, value),
                'Least Squares': np.linalg.lstsq(x, value)
            }
        return linal_fx_dict
    else:
        print("Arrays are not of the same shape")

In [258]:
arr_selection = 2
fx_selection = 5
try:
    selected_arrays = random.sample(can_multiply1, arr_selection)
    print(f"""
Selected Arrays:
1.{selected_arrays[0].shape} 
{selected_arrays[0]}

2. {selected_arrays[1].shape} 
{selected_arrays[1]} 
{'*'*50}""")
    random_choice(x=[selected_arrays[0],selected_arrays[1]], y=fx_selection, fx=linalg_func)

except AttributeError as e:
    print("Unable to perform linear algebra operations on arrays of different sizes")


Selected Arrays:
1.(2, 4) 
[[0.43708335 0.47375514 0.64303437 0.39134   ]
 [0.57665114 0.07394579 0.1952765  0.42283307]]

2. (4, 2) 
[[0.35962622 0.7963181 ]
 [0.60623123 0.38959353]
 [0.19741157 0.01166917]
 [0.84594256 0.50675782]] 
**************************************************
Arrays are not of the same shape
Unable to perform linear algebra operations on arrays of different sizes


In [257]:

can_multiply1[0].shape[0] == can_multiply1[1].shape[1]

True